/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mrljdx_security_SecurityUtils */

#ifndef _Included_com_mrljdx_security_SecurityUtils
#define _Included_com_mrljdx_security_SecurityUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mrljdx_security_SecurityUtils
 * Method:    nativeMD5Str
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mrljdx_security_SecurityUtils_nativeMD5Str
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mrljdx_security_SecurityUtils
 * Method:    nativeSHAStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mrljdx_security_SecurityUtils_nativeSHAStr
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
